version: "3.7"
services:
  mysql-docker-boot:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: kyaw
      MYSQL_ROOT_PASSWORD: p4SSW0rd