
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: employeeService
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employee/**
        - id: addressService
          uri: lb://ADDRESS-SERVICE
          predicates:
            - Path=/address/**
        - id: webuiService
          uri: lb://WEB-UI
          predicates:
            - Path=/webui/**,/bootstrap/**